# mkdocs.yml
site_name: Classifier projects
nav:
  - Home: index.md
  - workflows:
      - main: src/main.md
  - src:
      - data: src/data.md
      - evaluate: src/evaluate.md
      - predict: src/predict.md
      - train: src/train.md
      - utils: src/utils.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - . # reload docs for any file changes

